CREATE TABLE MENTAL_HEALTH_HUB.PUBLIC.DISORDER_METRICS(
    ID INT PRIMARY KEY,
    YEAR INT,
    PREVALENCE FLOAT,
    AGE_INTERVAL VARCHAR,
    COUNTRY_ID VARCHAR REFERENCES COUNTRY (COUNTRY_ID),
    DISORDER_ID VARCHAR REFERENCES DISORDER (DISORDER_ID)
);