CREATE TABLE MENTAL_HEALTH_HUB.PUBLIC.DISORDER_METRICS(
    ID INT PRIMARY KEY,
    YEAR INT,
    PREVALENCE FLOAT,
    PREVALENCE_AGE_STANDARDIZED FLOAT,
    NUMBER_OF_CASES INT,
    COUNTRY_ID VARCHAR REFERENCES COUNTRY (COUNTRY_ID),
    DISORDER_ID VARCHAR REFERENCES DISORDER (DISORDER_ID)
);

CREATE TABLE MENTAL_HEALTH_HUB.PUBLIC.Mental_Health_Indicators(
    ID INT PRIMARY KEY,
    YEAR INT,
    VALUE FLOAT,
    country_id INT REFERENCES Country(country_id),
    indicator_id INT REFERENCES Indicator(indicator_id)
);

CREATE TABLE MENTAL_HEALTH_HUB.PUBLIC.DISORDER_METRICS(
    ID INT PRIMARY KEY,
    YEAR INT,
    PREVALENCE FLOAT,
    AGE_INTERVAL VARCHAR,
    COUNTRY_ID VARCHAR REFERENCES COUNTRY (COUNTRY_ID),
    DISORDER_ID VARCHAR REFERENCES DISORDER (DISORDER_ID)
);

CREATE TABLE MENTAL_HEALTH_HUB.PUBLIC.social_economical_metrics(
    id INT,
    year INT,
    value FLOAT,
    FOREIGN KEY (country_id) REFERENCES country(id), 
    FOREIGN KEY (metric_id) REFERENCES metric(id)
);