-- creating the Database
CREATE DATABASE MENTAL_HEALTH_HUB;

-- Creating Schemas
CREATE SCHEMA datasets;

-- Creating a role for the group
CREATE ROLE G32
GRANT ROLE G32 TO USER BULLFROG
GRANT ROLE G32 TO USER FALCON
GRANT ROLE G32 TO USER HEDGEHOG

-- Assigning privileges to our role
GRANT ALL PRIVILEGES ON DATABASE MENTAL_HEALTH_HUB TO ROLE G32

GRANT ALL PRIVILEGES ON SCHEMA MENTAL_HEALTH_HUB.Public TO ROLE G32
GRANT USAGE ON SCHEMA MENTAL_HEALTH_HUB.Public TO ROLE G32

GRANT ALL PRIVILEGES ON SCHEMA MENTAL_HEALTH_HUB.datasets TO ROLE G32
GRANT USAGE ON SCHEMA MENTAL_HEALTH_HUB.datasets TO ROLE G32
